### ISSUE TITLE
ImmutableList support Release

### ISSUE THREAD

**Issue by hackersOfhackers** [magro/kryo-serializers#27]
Hi,
please release latest version of kryo-serializers that have support for guava's ImmutableList.

**Comment by magro** [comment]
Do you want to submit a pull request that adds support for guava's ImmutableList?

**Comment by hackersOfhackers** [comment]
No..Actually guava's ImmutableList support is already submitted by y-higuchi. I want to add this as a Maven dependency. so 0.27 version of Kryo-serizlizers does not include this support. So please release latest version of kryo-serializers.

**Comment by magro** [comment]
Ah, right. I just pushed 0.28 to maven central, should be visible in the next hour.

**Comment by hackersOfhackers** [comment]
Thank u so much.
