### ISSUE TITLE
Joda-Time DateTime serializer shouldn't "optimize" default time zone

### ISSUE THREAD

**Issue by RenniePet** [magro/kryo-serializers#30]
This is a hypothetical problem - I haven't personally a case that would be affected by this, but I can imagine that it could be a problem.

The serializer for Joda-Time DateTime tests if the associated time zone is the default time zone, and serializes that to en empty string. The deserializer, when it receives an empty string, then uses the default time zone on the receiving system. 

This is duly documented in the comments: "If the time zone is the default time zone ({@link DateTimeZone#getDefault()}), the time zone attribute is omitted. This requires different machines to have the same time zone settings."

So if two machines in different time zones are communicating via Kryo and using Joda-Time DateTime with their time zones set to the default time zone, things are going to go wrong. 

It can maybe be argued that you shouldn't use DateTime in that way. DateTime is more typically used with the time zone set to UTC, so then there isn't a problem. Except that maybe one of the machines is a server, and its time zone actually is set to UTC, so UTC the default for that system but not for the client systems.

My suggestion: remove that "optimization" and always send the time zone info. Or is is conceivable that some usage of this program is now dependent on this behavior, so doing that would be a "breaking change"?

**Comment by magro** [comment]
Good catch! I think we can change the serialization side to fix this and don't break existing installations. Would you like to submit a pull request?

**Comment by tinnet** [comment]
i create a PR for this @magro @RenniePet :)
