### ISSUE TITLE
Supports kryo 3.0?

### ISSUE THREAD

**Issue by chakrit** [magro/kryo-serializers#31]
I assume it does not at the moment?

What is there to be done until this can be shipped with 3.0 support?

**Comment by magro** [comment]
The latest version should already work with kryo 3. Upgrading kryo-serializers to kryo 3 should be no more than pushing the version in pom.xml.

**Comment by keesvandieren** [comment]
I got issues on Android with Gradle.

Android dexer complains on duplicated classes. I think this is because groupId of kryo 3 has changed.

Downgraded to kry 2.2.4 for so long, which works well for me.

**Comment by magro** [comment]
I just released kryo-serializers 0.29 which uses kryo-3.0.1 (kryo-serializers itself is fully compatible with previous versions).
