### ISSUE TITLE
osgi import is broken for kryo

### ISSUE THREAD

**Issue by maiser** [magro/kryo-serializers#42]
Hi all,

You still refer to the < 3.0 version of kryo in your osgi import statement - even if you have kryo 3.0 in your dependencies:

com.esotericsoftware.kryo*;version="[2.24.0,3.0)",

It would be great if you could fix this - i'll use a manually patched version in the meantime.

Thanks,
Mathias

**Comment by magro** [comment]
Good catch, thanks for the report! Do you want to submit a pull request? This would speed things up :-)

**Comment by maiser** [comment]
would be great if you could publish a new version with the fix

**Comment by magro** [comment]
Thanks for the pull request, released as 0.37 to maven central.
