### ISSUE TITLE
Arrays.asList produced collection is not immutable

### ISSUE THREAD

**Issue by betalb** [magro/kryo-serializers#46]
Arrays.asList serializer doesn't properly support copy method, as simply returns original collection. But child elements of this collection are not immutable

**Comment by rchenv** [comment]
any workaround if this is not addressed soon?

**Comment by magro** [comment]
Sorry for the delay. To mention it, you can always submit a pull request. ;-)

**Comment by magro** [comment]
#79 had to be reverted because it broke the build / tests, see #85
