### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by 3xp0n3nt** [magro/kryo-serializers#51]
When are we going to get a new release? It looks like there hasn't been one since October 2015. It would also be nice if you published snapshots to Sonatype.

**Comment by 3xp0n3nt** [comment]
Ok, I guess my PR has been the only non-trivial change to the library since the last release. Is it enough to warrant a release, since it's been quite a while?

**Comment by magro** [comment]
I just published 0.38, will take some minutes until it's in maven central. For snapshot publishing I'd need to figure out how this can be done via travis (encrypting credentials), but right now I'm fairly loaded and don't see when I'll have time for this. I can always publish releases on request as it takes only a couple of minutes, if you really would like to have snapshots please submit a separate issue for this or even submit a PR with some comments what I'd need to adjust :-)

**Comment by 3xp0n3nt** [comment]
All right, thanks for the release!
