### ISSUE TITLE
Make protocol buffers a separate dependency

### ISSUE THREAD

**Issue by pakoito** [magro/kryo-serializers#59]
I am using a library that requires kryo-serializers as a dependency, called [PaperDb](https://github.com/pilgr/Paper). The library doesn't use any protobuf, but because of this dependency it adds almost ~7k methods because of it. In Android, method count is highly important because it affects app startup time, and some limitations around 65k methods before some VM hackery is required.

Sadly, the dependency cannot be transitively removed by maven/gradle either. I'd like to ask that a separate module is created containing just the protobuf code and dependency, if possible.

**Comment by magro** [comment]
Before considering a separate module for the protobuf serializer I'd try to set scope=provided or optional=true. Do you want to submit a pull request for this?

**Comment by pakoito** [comment]
Can do! Is there any reason why it wasn't optional from the start, like joda-time?

**Comment by pakoito** [comment]
I'm more comfortable with Gradle than with Maven, but I believe there is no need for changes in the code to accommodate `optional=true`, right?

**Comment by magro** [comment]
That's what I asked myself :-)
