### ISSUE TITLE
Import-Package's kryo version range is wrong in the pom.xml.

### ISSUE THREAD

**Issue by ranerp** [magro/kryo-serializers#67]
I am not able to install Eclipse plugin that contains kryo-serializers due to not finding the correct version of kryo, even when the kryo 4.0.0 dependency is available.

`  Missing requirement: kryo serializers 0.41.0 (de.javakaffee.kryo-serializers 0.41.0) requires 'package com.esotericsoftware.kryo [3.0.3,4.0.0)' but it could not be found`

As I started to look in the pom.xml I found this:

`
<instructions>

    <Import-Package><![CDATA[
        com.esotericsoftware.kryo*;version="[3.0.3,4.0)",
        esotericsoftware.minlog*;version="[1.2,2.0)",
        reflect;resolution:=optional,*]]>
    </Import-Package>
</instructions>
`

Shouldn't it be [3.0.3, 4.0] or [3.0.3, 5.0)?

**Comment by magro** [comment]
Fixed with #82 / commit d3c3c7c
