### ISSUE TITLE
Supports Kryo 4.0?

### ISSUE THREAD

**Issue by Tostino** [magro/kryo-serializers#68]
Does the latest release support Kryo 4.0.x?  It explicitly states that it supports 2/3, but no mention of 4.

**Comment by magro** [comment]
Yes, it should. If it doesn't please submit an issue, thanks!

**Comment by gmtjlmartin** [comment]
Please update the main page for this github project to indicate that the serailizers provided with this project are compatible with kryo V4.   BTW, thanks for making these available.

**Comment by magro** [comment]
Do you want to submit a PR?

**Comment by fabienrenaud** [comment]
https://github.com/magro/kryo-serializers/pull/75

**Comment by magro** [comment]
Closed with #75
