### ISSUE TITLE
ImmutableList serializer registration incomplete

### ISSUE THREAD

**Issue by ec-omikron** [magro/kryo-serializers#72]
The ImmutableListSerializer attempts to register ImmutableList$Sublist like this

    kryo.register(ImmutableList.of(1,2,3).subList(1, 2).getClass(), serializer);

However length 1 sublists are actually of type SingletonImmutableLists now so this method no longer works.

**Comment by magro** [comment]
Do you want to submit a pull request?

**Comment by fabienrenaud** [comment]
I see the fix was merged to master but not released yet to central repos. When is the next release?

**Comment by magro** [comment]
I just pushed 0.42 to maven central. Thanks for reminding! :-)
