### ISSUE TITLE
Why add 1

### ISSUE THREAD

**Issue by yuanyifang** [magro/kryo-serializers#80]
https://github.com/magro/kryo-serializers/blob/e334698ec876f5153745a957e1cbfaf41ad4bc28/src/main/java/de/javakaffee/kryoserializers/protobuf/ProtobufSerializer.java#L33

**Comment by mkozioro** [comment]
Hi,

From Kryo output class:
`	/** Writes a 1-5 byte int. It is guaranteed that a varible length encoding will be used.
	 * 
	 * @param optimizePositive If true, small positive numbers will be more efficient (1 byte) and small negative numbers will be
	 *           inefficient (5 bytes). */
	public int writeVarInt (int value, boolean optimizePositive) throws KryoException {`

+ 1 is used to have here always positive number.

**Comment by magro** [comment]
@mkozioro thanks for commenting!
