### ISSUE TITLE
OSGi version of kryo-serializers does not provides support for 4.0.x kryo dependency

### ISSUE THREAD

**Issue by imonteroperez** [magro/kryo-serializers#83]
Although com.esotericsoftware.kryo dependency is provided inside pom.xml dependencies block with version 4.0.0, you are not including it in generated MANIFEST.MF file due to com.esotericsoftware.kryo*;version="[3.0.3,4.0)"

I created a PR https://github.com/magro/kryo-serializers/pull/82

**Comment by magro** [comment]
Closed with #82.
