### ISSUE TITLE
Use writeVarInt for enum ordinals

### ISSUE THREAD

**Issue by shevek** [magro/kryo-serializers#95]
In things like EnumMapSerializer, VarInt encoding is smaller than int encoding for both lengths and ordinal() values. Please prefer it.

**Comment by magro** [comment]
Which serializer are you referring to? Do you want to submit a PR?

**Comment by shevek** [comment]
https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/EnumMapSerializer.java#L96

Should use writeVarInt() to save 3 bytes.

**Comment by magro** [comment]
Right. As said, feel free to submit a PR!
