### ISSUE TITLE
Support Kryo#copy for Guava Multimaps

### ISSUE THREAD

**Issue by f4lco** [magro/kryo-serializers#99]
As stated in the Javadoc of the Guava multimap serializers (e.g., `ArrayListMultimapSerializer`), `Kryo#copy` is not supported yet. 

To me it appears not too difficult to implement. Am I overlooking something? Is there any good reason why this has not already been implemented, @magro? If not, I'd be glad to file a PR.

**Comment by magro** [comment]
@f4lco I don't think that there's a good reason, so a PR would be great!
